name: daily-cron
on:
  schedule:
    - cron: '*/10 * * * * *'
jobs:
  cron:
    runs-on: ubuntu-latest
    steps:
      - name: Call our API route
        run: |
          curl --request GET \
          --url 'https://backend-price-tracker-3q8l.vercel.app/api/TrackingProduct' \
          --header 'Authorization: Bearer ${{ secrets.API_SECRET_KEY }}'